### ISSUE TITLE
Resque Web does not work with 1.25.2

### ISSUE THREAD

**Issue by mikelitton** [resque/resque#1200]
Trying to view the scheduler in you get the following problem:

NoMethodError - undefined method `constantize' for Resque Client connected to redis
