### ISSUE TITLE
Getting "undefined method `tagged' for #<Resque::QuietFormatter>" since upgrading to 1.26.0

### ISSUE THREAD

**Issue by BrentWheeldon** [resque/resque#1431]
Hi there,

We upgraded from 1.25.2 to 1.26.0 earlier in the week and saw this no method error this morning:

```
Rack app error: #<NoMethodError: undefined method `tagged' for #<Resque::QuietFormatter:0x007f9ec136c128>> 
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/tagged_logging.rb:68:in `tagged' 
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/rack/logger.rb:20:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/request_id.rb:21:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.5.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/static.rb:116:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/ssl.rb:24:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/honeybadger-2.5.3/lib/honeybadger/rack/error_notifier.rb:33:in `block in call' 
/app/vendor/bundle/ruby/2.3.0/gems/honeybadger-2.5.3/lib/honeybadger/config.rb:198:in `with_request' 
/app/vendor/bundle/ruby/2.3.0/gems/honeybadger-2.5.3/lib/honeybadger/rack/error_notifier.rb:30:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/honeybadger-2.5.3/lib/honeybadger/rack/user_feedback.rb:28:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb:227:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:561:in `handle_request' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:406:in `process_client' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:271:in `block in run' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread' 
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/engine.rb:518:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.2/lib/rails/application.rb:165:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/newrelic_rpm-3.15.0.314/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb:227:in `call' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:561:in `handle_request' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:406:in `process_client' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:271:in `block in run' 
/app/vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread' 
```

A restart of the app server fixed the issue, but it's unclear why an app server would be using the ResqueLogger? I'm digging in more and will post an update with what I find, but thought I'd throw this out there to see if anyone else had seen it.

Cheers,

Brent

**Comment by steveklabnik** [comment]
Interesting, it's not clear to me either. Let me know if you find something, and I'll try to poke at things too.

**Comment by BrentWheeldon** [comment]
So it turns out that this starts happening when someone goes to the resque web interface. We're setting that up in our routes like:

```
mount Resque::Server => "/resque"
```

Rolling back to 1.25.2 fixes this issue.

**Comment by sirmike** [comment]
Similar issue here:

```
E, [2016-05-02T10:38:45.458244 #28457] ERROR -- : app error: undefined method `clear_tags!' for #<Resque::QuietFormatter:0x0000000567d8d8> (NoMethodError)
E, [2016-05-02T10:38:45.458542 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:65:in `clear_tags!'
E, [2016-05-02T10:38:45.458699 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:72:in `flush'
E, [2016-05-02T10:38:45.458846 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/log_subscriber.rb:70:in `flush_all!'
E, [2016-05-02T10:38:45.458988 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:45:in `call_app'
E, [2016-05-02T10:38:45.459130 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
E, [2016-05-02T10:38:45.459237 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
E, [2016-05-02T10:38:45.459322 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
E, [2016-05-02T10:38:45.459406 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
E, [2016-05-02T10:38:45.459508 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
E, [2016-05-02T10:38:45.459592 #28457] ERROR -- : /opt/myapp/releases/20160502082709/config/initializers/quiet_assets.rb:5:in `call_with_quiet_assets'
E, [2016-05-02T10:38:45.459675 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
E, [2016-05-02T10:38:45.459758 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
E, [2016-05-02T10:38:45.459840 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
E, [2016-05-02T10:38:45.459923 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
E, [2016-05-02T10:38:45.460005 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
E, [2016-05-02T10:38:45.460088 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
E, [2016-05-02T10:38:45.460170 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
E, [2016-05-02T10:38:45.460261 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
E, [2016-05-02T10:38:45.460343 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
E, [2016-05-02T10:38:45.460426 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
E, [2016-05-02T10:38:45.460523 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:576:in `process_client'
E, [2016-05-02T10:38:45.460630 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
E, [2016-05-02T10:38:45.460715 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
E, [2016-05-02T10:38:45.460898 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
E, [2016-05-02T10:38:45.460986 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
E, [2016-05-02T10:38:45.461075 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
E, [2016-05-02T10:38:45.461198 #28457] ERROR -- : /opt/myapp/shared/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
7
```

I reproduced the problem and it seems to happen when I start a resque worker and go to resque web dashboard. Unicorn worker which tries to process this request starts returning error 500 and stops processing requests until restarted.

Without resque workers running, problem does not occur.

Ruby 2.2.3
Unicorn 4.8.3
Resque 1.26

**Comment by chrisccerami** [comment]
After looking into this for a bit here's some information I've gathered. The `QuietFormatter` (and the other 2 formatters) haven't changed in years, so the problem presumably isn't there. The `tagged` and `clear_tags!` displayed in these stacktaces come from `ActiveSupport::TaggedLogging` (http://api.rubyonrails.org/classes/ActiveSupport/TaggedLogging.html), which should wrap the Resque.logger (which is a MonoLogger) and provide some extra methods to handle tagging. It should also do the same with the logger's formatter.

Here's my current best theory as to what's happening, although I may be on the entirely wrong track. It seems like it might be possible that the problem is being caused by the act of changing the logging level of `Resque.logger` after `TaggedLogging` has been initialized. Here's the rundown of what I believe is happening.

1. `Resque.logger` is set to `MonoLogger.new` and it's formatter is by default the `QuietFormatter`.
2. 'ActiveSupport::TaggedLogging` wraps both that logger and its formatter in its tagging methods.
3. `Resque.logger.formatter` is set to `VerboseFormatter`, which has not been wrapped by TaggedLogging at its initialization.
4. The new tagged logger tries to call a tagging method on the formatter, which doesn't have that method.

Obviously this could also happen when switching to QuietFormatter or VeryVerboseFormatter, but that's just an example of what I think is happening (you can see the same situation described [here](https://cbpowell.wordpress.com/2013/08/09/beautiful-logging-for-ruby-on-rails-4/) in the comments) .

It seems to me like this is essentially the same bug as described in https://github.com/rails/rails/issues/19439, which is a bug with `ActiveSupport::TaggedLogging`, and not actually with Resque.

**Comment by Zhomart** [comment]
I'm getting same error. I found that `Reque::Worker#verbose=` is being called.

This is a call stack:
```
>> Resque verbose=nil
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:130:in `initialize'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:94:in `new'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:94:in `find'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:56:in `block in all'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:56:in `map'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:56:in `all'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/worker.rb:62:in `working'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque.rb:468:in `working'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/working.erb:30:in `block in singleton class'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/working.erb:-6:in `instance_eval'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/working.erb:-6:in `singleton class'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/working.erb:-8:in `__tilt_70237900182240'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:667:in `erb'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server.rb:128:in `partial'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/overview.erb:3:in `block in singleton class'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/overview.erb:-6:in `instance_eval'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/overview.erb:-6:in `singleton class'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server/views/overview.erb:-8:in `__tilt_70237900182240'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `call'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:167:in `evaluate'
>> /usr/local/bundle/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:823:in `render'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:667:in `erb'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server.rb:147:in `show'
>> /usr/local/bundle/bundler/gems/resque-355f95098eec/lib/resque/server.rb:176:in `block (2 levels) in <class:Server>'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>> /usr/local/bundle/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
>> /usr/local/bundle/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb:51:in `serve'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:43:in `block in serve'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `each'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb:30:in `serve'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb:817:in `call'
>> /usr/local/bundle/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
>> /usr/local/bundle/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
>> /usr/local/bundle/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb:260:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>> /usr/local/bundle/gems/rollbar-2.11.5/lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
>> /usr/local/bundle/gems/rollbar-2.11.5/lib/rollbar.rb:735:in `scoped'
>> /usr/local/bundle/gems/rollbar-2.11.5/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>> /usr/local/bundle/gems/rollbar-2.11.5/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>> /usr/local/bundle/gems/lograge-0.3.6/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
>> /usr/local/bundle/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `block in call'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:26:in `tagged'
>> /usr/local/bundle/gems/activesupport-4.2.6/lib/active_support/tagged_logging.rb:68:in `tagged'
>> /usr/local/bundle/gems/railties-4.2.6/lib/rails/rack/logger.rb:20:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
>> /usr/local/bundle/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb:120:in `call'
>> /usr/local/bundle/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
>> /usr/local/bundle/gems/rack-mini-profiler-0.10.1/lib/mini_profiler/profiler.rb:278:in `call'
>> /usr/local/bundle/gems/railties-4.2.6/lib/rails/engine.rb:518:in `call'
>> /usr/local/bundle/gems/railties-4.2.6/lib/rails/application.rb:165:in `call'
>> /usr/local/bundle/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
>> /usr/local/bundle/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
>> /usr/local/bundle/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
>> /usr/local/bundle/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
>> /usr/local/bundle/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by Zhomart** [comment]
So I use puma web server 3.4.0, I've just checked and I see that `Resque::Worker.new`, which calls `Resque::Worker#verbose=`, is called by different thread.

**Comment by Zhomart** [comment]
I solved it, problem was in my code. I have created my own logger `MultiLogger`.
I solved it by creating method `MultiLogger#dup` that duplicated multi logger instance,
and then assigned resque new logger `Resque.logger = Rails.logger.dup`.

**Comment by chrisccerami** [comment]
:+1: thanks for the info @Zhomart. Might be useful to others who have this problem in the future.

**Comment by topofocus** [comment]
I had a similar problem. 
This thread was a great help.

Working on a rails5 project using orientdb as database ( https://github.com/topofocus/active-orient )
In the gem I used 
``
57 logger.formatter = proc do |severity, datetime, progname, msg|
 58   "#{datetime.strftime("%d.%m.(%X)")}#{"%5s" % severity}->#{msg}\n"
 59 end
``
After commenting this, rails stopped complaining about a missing tagged - method.
