### ISSUE TITLE
Error: undefined method `connect' for Redis:Class (NoMethodError)

### ISSUE THREAD

**Issue by DannyBen** [resque/resque#1614]
There seems to be a problem when the redis 4.0 gem is installed.

```
/gems/resque-1.27.4/lib/resque.rb:116:in `redis=': undefined method `connect' for Redis:Class (NoMethodError)
```

this code:

```ruby
# test.rb
require 'resque'
ENV['QUEUE'] = '*'
worker = Resque::Worker.new
Resque.redis = 'redis://redis:6379'
```

Works with no problems with the redis 3.5 gem, but fails with the redis 4.0 gem

In addition to the above test file, I only have this Gemfile, provided here for convenience and quick reproduction:

```ruby
# Gemfile
source "https://rubygems.org"
gem "resque"

# Does not work with redis 4.0, so we force it
# gem 'redis', '< 4.0'
```

**Comment by rafaelfranca** [comment]
Can you try with the resque master branch? I believe this issue is already fixed.

**Comment by DannyBen** [comment]
Tried with resque 2.0.0 (was 1.27.4), and it is indeed fixed, thanks. 
Will wait for the release, and in the meantime force `redis < 4.0`

**Comment by jeremy** [comment]
#1593 👍
