### ISSUE TITLE
Version 1.19.0 raises exception on Rails 2.3.14 when starting rake task

### ISSUE THREAD

**Issue by brianjlandau** [resque/resque#477]
I'm working on a Rails 2.3.14 application and installed Resque. When I run `QUEUE=* VVERBOSE=1 rake --trace resque:work` I get this exception:

```
NoMethodError: undefined method `cache_classes' for nil:NilClass
from vendor/bundler_gems/ruby/1.8/gems/activesupport-2.3.14/lib/active_support/whiny_nil.rb:52:in `method_missing'
from vendor/bundler_gems/ruby/1.8/gems/rails-2.3.14/lib/initializer.rb:414:in `load_application_classes'
from vendor/bundler_gems/ruby/1.8/gems/rails-2.3.14/lib/initializer.rb:115:in `send'
from vendor/bundler_gems/ruby/1.8/gems/rails-2.3.14/lib/initializer.rb:115:in `run'
from (irb):1
```

To solve this I downgraded Resque to version 1.18.5
