### ISSUE TITLE
undefined method `is_a?' for <Redis::Future [:sadd, "resque:queues", "synchronisations"]>:Redis::Future

### ISSUE THREAD

**Issue by lucidstack** [resque/resque#1142]
After upgrading resque version from 1.24.1 to 1.25.1, calling enqueue raise the exception reported in the title, as the redis-namespace gem version has to be at least 1.3.x  (which is pointing to the redis gem version 3.0.4, which implements the missing is_a? method for Redis::Future).
