### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass since Ruby 3.3.0dev

### ISSUE THREAD

**Issue by yahonda** [resque/resque#1856]
Recently, one of Rails CI testing Active Job integration tests with `resque` has been failing. https://buildkite.com/rails/rails/builds/93710#01863c1c-deb5-4ec2-9169-636a5ffbcbbc/1359-1416

Based on the `git bisect` or Ruby repository, this behavior change has been introduced via https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1

So far I am not sure how to address it from Ruby side or resque side though, I'm opening an issue here.

### Steps to reproduce
```
Install `ruby 3.3.0dev` includes https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1
git clone https://github.com/resque/resque.git
cd resque
bundle install
bundle exec rake test
```

### Expected behavior 
All of tests should pass.

### Actual behavior
```
283 runs, 490 assertions, 8 failures, 80 errors, 0 skips
```

These failures and errors are triggered since https://github.com/ruby/ruby/commit/194520f80e1cdb71faa055d731450855a1ddb8d1

```ruby
$ bundle exec rake test
/home/yahonda/.rbenv/versions/trunk/bin/ruby -w -I"lib:test:lib" /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/airbrake_test.rb" "test/child_killing_test.rb" "test/failure_base_test.rb" "test/job_hooks_test.rb" "test/job_plugins_test.rb" "test/logging_test.rb" "test/plugin_test.rb" "test/rake_test.rb" "test/resque-web_runner_test.rb" "test/resque-web_test.rb" "test/resque_failure_multi_queue_test.rb" "test/resque_failure_multiple_test.rb" "test/resque_failure_redis_test.rb" "test/resque_hook_test.rb" "test/resque_test.rb" "test/server_helper_test.rb" "test/stat_test.rb" "test/worker_test.rb"
/usr/bin/redis-server
Starting redis for testing at localhost:9736...
Install airbrake gem to run Airbrake tests.
Run options: --seed 56557

# Running:

...................E........E.............E........................EE............../home/yahonda/.rbenv/versions/trunk/lib/ruby/3.3.0+0/logger.rb:385:in `level': undefined method `[]' for nil:NilClass (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.3.0+0/logger.rb:654:in `add'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/3.3.0+0/logger.rb:710:in `error'
	from /home/yahonda/src/github.com/resque/resque/lib/resque/logging.rb:8:in `log'
	from /home/yahonda/src/github.com/resque/resque/lib/resque/worker.rb:945:in `log_with_severity'
	from /home/yahonda/src/github.com/resque/resque/lib/resque/worker.rb:262:in `rescue in work'
	from /home/yahonda/src/github.com/resque/resque/lib/resque/worker.rb:242:in `work'
	from /home/yahonda/src/github.com/resque/resque/test/child_killing_test.rb:34:in `block (2 levels) in start_worker'
	from /home/yahonda/src/github.com/resque/resque/test/test_helper.rb:247:in `suppress_warnings'
	from /home/yahonda/src/github.com/resque/resque/test/child_killing_test.rb:33:in `block in start_worker'
	from /home/yahonda/src/github.com/resque/resque/test/child_killing_test.rb:25:in `fork'
	from /home/yahonda/src/github.com/resque/resque/test/child_killing_test.rb:25:in `start_worker'
	from /home/yahonda/src/github.com/resque/resque/test/child_killing_test.rb:71:in `block (2 levels) in <top (required)>'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:102:in `block (3 levels) in run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:199:in `capture_exceptions'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:97:in `block (2 levels) in run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:296:in `time_it'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:96:in `block in run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:391:in `on_signal'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:247:in `with_info_handler'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest/test.rb:95:in `run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:1051:in `run_one_method'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:365:in `run_one_method'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:352:in `block (2 levels) in run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:351:in `each'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:351:in `block in run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:391:in `on_signal'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:378:in `with_info_handler'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:350:in `run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:182:in `block in __run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:182:in `map'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:182:in `__run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:159:in `run'
	from /home/yahonda/.rbenv/versions/trunk/lib/ruby/gems/3.3.0+0/gems/minitest-5.17.0/lib/minitest.rb:83:in `block in autorun'
/home/yahonda/.rbenv/versions/trunk/lib/ruby/3.3.0+0/logger.rb:385:in `level': undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by jeremyevans** [comment]
`@level_override` is set in `Logger#initialize`. The only thing that comes to mind that could cause this is someone is overriding `Logger#initialize` and not calling `super`.

**Comment by sambostock** [comment]
https://github.com/Shopify/job-iteration/actions/runs/4185456672/jobs/7252537151 now passes with Ruby HEAD & my branch of `mono_logger`, which is where I noticed the issue.

**Comment by yahonda** [comment]
Thanks for the fix.

Confirmed https://github.com/steveklabnik/mono_logger/pull/12 addresses this issue
by setting Gemfile as follows.

```diff
$ git diff
diff --git a/Gemfile b/Gemfile
index b78f7439..cbb5bde5 100644
--- a/Gemfile
+++ b/Gemfile
@@ -15,3 +15,4 @@ gem "rack-test", "~> 2.0"
 gem "rake"
 gem "rubocop", "~> 0.80"
 gem "pry"
+gem "mono_logger", github: "sambostock/mono_logger", branch: "ruby-head-support"
$
```

**Comment by zzak** [comment]
Also confirmed adding this to rails Gemfile fixes the Active Job tests on Ruby 3.3.0 🙏

**Comment by PatrickTulskie** [comment]
If I'm understanding this correctly, this was resolved in `mono_logger`. Any objection to closing out this issue?

**Comment by yahonda** [comment]
Correct. Closing this issue. Thank you for the notification.

**Comment by PatrickTulskie** [comment]
Thanks @yahonda. I'll probably bump the `mono_logger` dependency once there's a new release on rubygems in a 2.6.x release so that we have baseline ruby 3.3 support.

**Comment by steveklabnik** [comment]
@PatrickTulskie shipped 1.1.2, you should be able to update, let me know if you run into any more issues.

**Comment by PatrickTulskie** [comment]
@steveklabnik thanks! Re-ran the CI and it looks like we're good to go on head for almost everything. Got something new to look into but at least the issues here seem resolved. Really appreciate it!
