### ISSUE TITLE
Undefined local variable or method `per_page'

### ISSUE THREAD

**Issue by JohnBat26** [resque/resque#892]
Hi all.
I use ruby-2.0.0-p0 и resque-1.24.0.
After update from 1.23.1  to 1.24.0 I begin to get next error:

``` ruby
undefined local variable or method `per_page' for #<Resque::Server:0x0000000a084d78>
```

at page: "Delayed Job" in Resque web client.
